app = "bun-chat-app"
primary_region = "bos"  # Boston - change to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3002"

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[processes]
  app = "bun run start"
  
[experimental]
  allowed_public_ports = []
  auto_rollback = true
  enable_consul = true
  private_network = true  # Enables communication between VMs